# generic
printme_qa_url=('https://prd2.printme.com/')
printme_prd_url=('https://prd2.printme.com/')

# LoginApps_and_drivers
get_started=('getStarted')
upload_files=('fileUploadTrigger')
send_btn=('pm-home-upload-send-button')
email_releasecode="//input[contains(@placeholder,'Enter email address for release code')]"
docid="//div[@class='emailCode medium col-12 col-lg-10 col-xl-9 force-select text-center']"
printme_logo="//img[@src='assets/img/PM-efi-Logo2.svg']"
explore_drpdwn="//a[@id='navbarDropdown1']"
Apps_and_drivers="//a[@class='dropdown-item'][1]"
PrintMe_for_business="//a[@class='dropdown-item'][2]"
Locate_a_printer="//a[@class='dropdown-item'][3]"
support_drpdwn="//a[@id='navbarDropdown2']"
FAQs="//a[@class='dropdown-item'][contains(text(),'FAQs')]"
Service_status="//a[@class='dropdown-item'][contains(text(),'Service status')]"
Support_center="//a[@class='dropdown-item'][contains(text(),'Support center')]"
Global_drpdwn="//img[@src='assets/img/Language.png']"
English="//div[@class='dropdown-menu pmsub-menu show']//a[1]"
English_International="//a[contains(text(),'English International')]"
Francis="//a[contains(text(),'Français')]"
Italiano="//a[contains(text(),'Italiano')]"
Deutsch="//a[contains(text(),'Deutsch')]"
Espanol="//a[contains(text(),'Español')]"
Nederlands="//a[contains(text(),'Nederlands')]"
Portuguese_brasil="//a[contains(text(),'Português brasileiro')]"
Learn_more="//a[contains(text(),'Learn more')]"
Download_apps_and_drivers="//div[@class='pm-body2-gray']//a"
Web_release="//a[contains(text(),'Web release')]"
Terms_of_use="//a[contains(text(),'Terms of use')]"
Privacy_policy="//a[contains(text(),'Privacy policy')]"
Contact_us="//a[contains(text(),'Contact us')]"
Copyright="//a[@class='text-nowrap']"
Download_the_iOS_app="//p[contains(text(),'Download the iOS app')]"
Download_the_Android_app="//p[contains(text(),'Download the Android app')]"
Supports_OSX_and_above="//p[contains(text(),'Supports OSX 10.10 and above')]"
Supports_Windows_and_10="//p[contains(text(),'Supports Windows 7, 8 and 10')]"
PrintMe_Service_Works="//div[contains(text(),'How does the PrintMe service work?')]"
this_site="//a[contains(text(),'this site')]"
Install_PrintMe="//div[contains(text(),'What do I need to install to use the PrintMe servi')]"
Cost_PrintMe="//div[contains(text(),'What does it cost to use the PrintMe service?')]"
File_types_and_sizes="//div[contains(text(),'What file types and file size can I use with the P')]"
Print_Documents="//div[contains(text(),'Do I need to know in advance where I will print my')]"
Interactive_Map="//div[@id='pm-faq-about05']//p[1]"
Locate_PrintMe_enabled="//div[contains(text(),'How do I locate a PrintMe-enabled printer?')]"
Interactive_Map1="//div[@id='pm-faq-about06']//p[1]"
Long_Print_Documents="//div[contains(text(),'How long do I have to print my documents?')]"
PrintMe_account="//div[contains(text(),'Do I need a PrintMe account?')]"
PrintMe_app="//div[contains(text(),'Do I need the PrintMe app?')]"
Print_boarding_pass="//div[contains(text(),'How can I print a boarding pass?')]"
this_website="//a[contains(text(),'this website')]"
PrintMe_mobile_apps="//div[contains(text(),'PrintMe mobile apps')]"
PrintMe_benefits="//div[contains(text(),'What are the benefits of using the PrintMe apps?')]"
Mobile_boarding_pass="//div[contains(text(),'How can I print a boarding pass using the mobile a')]"
Share_menu="//div[contains(text(),'How do I make PrintMe appear in the Share menu on ')]"
PrintMe_drs="//a[@class='pm-faq-menu-item collapsed row']//div[@class='col pl-2'][contains(text(),'PrintMe drivers')]"
PrintMe_drs_benefits ="//div[contains(text(),'What are the benefits of using the PrintMe drivers')]"
PrintMe_drs_upload="//div[contains(text(),'How do I upload a file using the PrintMe driver?')]"
PrintMe_drs_boarding="//div[contains(text(),'How can I print a boarding pass using the PrintMe ')]"
PrintMe_drs_install="//div[contains(text(),'Can I install the PrintMe driver with a script?')]"
PrintMe_Embedded="//a[@class='pm-faq-menu-item collapsed row']//div[@class='col pl-2'][contains(text(),'PrintMe Embedded')]"
PrintMe_Canon="//div[contains(text(),'Does my Canon engine support PrintMe Embedded?')]"
Canon_website="//a[contains(text(),'Canon website')]"
PrintMe_Security="//div[contains(text(),'Security')]"
PrintMe_secure="//div[contains(text(),'Is using the PrintMe service secure?')]"
PrintMe_Support="//div[contains(text(),'Support')]"
Status_page="//a[contains(text(),'Status page')]"
EFI_Smart_Support="//a[contains(text(),'EFI Smart Support')]"
PrintMe_experience="//div[contains(text(),'Are you experiencing an issue with PrintMe?')]"
Map_Search="//input[@placeholder='City, State or ZIP Code']"
Map_button="//img[@class='pl-1 pointer search']"
